BookingManagement/urls.py
"""
    BookingManagement URL Configuration
"""

from django.contrib import admin
from django.urls import path, include, re_path as url

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),

    url(r"^", include(("accountmgmt.urls", "accountmgmt"), namespace="accountmgmt")),

    url(r"^", include(("eventmgmt.urls", "eventmgmt"), namespace="eventmgmt")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

eventmgmt/urls.py
"""
  Urls file docs
"""
from django.urls import path
from eventmgmt import views

urlpatterns = [
    path("my/event/list", views.BookedEventDetailView.as_view(), name="my-event-list"),

    path("new/event/booking/list", views.NewBookingEventView.as_view(), name="new-event-booking"),

    path('new/event/booking/seat/<int:event_id>/', views.SeatBookingView.as_view(),
         name="seat-booking"),
    path('new/event/cancel/seat/<int:booked_event_id>/', views.SeatCancelView.as_view(),
         name="seat-cancel"),

]

templates/event/my-event-details.html
{% include 'base.html' %}

{% load static %}

<div class="my-event-list">
    {% include 'common/my-event-list.html' %}
</div>

<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="{% static 'lib/js/cookie.js' %}"></script>
<script src="{% static 'js/custom.js' %}"></script>

templates/event/new-event-booking-details.html
{% include 'base.html' %}

{% load static %}
<!-- Modal -->
<div class="featured-product">
    <div class="container">
        <div class="section-header">
            <h3>New Events</h3>
        </div>
        {% if all_new_event_booking %}
        <div class="row align-items-center product-slider product-slider-4">
            {% for evnt in all_new_event_booking %}
            <div class="col-lg-3">
                <div class="product-item">
                    <div class="product-image">
                        <a href="#event_modal{{evnt.id}}">
                            <img src="{% static 'images/default-event.png' %}" alt="Event Image">
                        </a>
                        <div class="product-action">

                            <a href="#event_modal{{evnt.id}}" data-toggle="modal" data-target="#event_modal{{evnt.id}}" style="width: 70px;height: 70px;">
                                <img src="{% static 'images/book_now.png' %}" style="-webkit-filter: none;">
                            </a>
                        </div>
                    </div>
                    <div class="product-content">
                        <div class="title">
                            <a href="#event_modal{{evnt.id}}">
                                {{evnt.event_id.event_name}} <b> - ({{evnt.event_type }})</b>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal fade" id="event_modal{{evnt.id}}" tabindex="-1" role="dialog" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLongTitle">{{evnt.event_id.event_name}}</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <div class="event-book-div">
                                <span>Event Start Date: <strong>{{evnt.event_id.event_start_date}} </strong></span><br>
                                <span>Event End Date: <strong>{{evnt.event_id.event_end_date}}</strong> </span><br>
                                <span>No Of Seats: <strong>{{evnt.event_id.no_of_seats}} </strong></span><br>
                                <span>Left Seats: <strong>{{evnt.event_id.left_seats}} </strong></span><br>
                                <span>Event Type: <strong>{{evnt.event_type }}</strong> </span><br>
                                <span>Event Price: <strong>{{evnt.event_price }} </strong></span><br>
                                {% if evnt.id in all_booked_event %}
                                    <strong>You have already booked this seat </strong>
                                {% elif evnt.event_id.left_seats == 0 %}
                                    <strong>All seat are booked.</strong>
                                {% endif %}
                                <strong class="text-danger" id="seat_success_{{ evnt.id }}"></strong>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-danger bg-danger" data-dismiss="modal">Close</button>
                            {% if not evnt.id in all_booked_event and evnt.event_id.left_seats != 0 %}
                            <button type="button" class="btn btn-primary" id="{{evnt.id}}" data-target="{% url 'eventmgmt:seat-booking' evnt.id  %}" onclick="event_book(this)">Book now</button>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>

            {% endfor %}
        </div>
        {% else %}
        No records found.
        {% endif %}
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="{% static 'lib/js/cookie.js' %}"></script>
<script src="{% static 'js/custom.js' %}"></script>