BookingManagement/urls.py
"""
    BookingManagement URL Configuration
"""

from django.contrib import admin
from django.urls import path, include, re_path as url

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),

    url(r"^", include(("accountmgmt.urls", "accountmgmt"), namespace="accountmgmt")),

    url(r"^", include(("eventmgmt.urls", "eventmgmt"), namespace="eventmgmt")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accountmgmt/urls.py
"""
    Used to manage all the URL's related to User Account
"""

from django.urls import path
from accountmgmt.views import HomeView, RegistrationView, LoginView, LogoutView

urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path('register/', RegistrationView.as_view(), name="signup"),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    # path('emailVerification/<uidb64>/<token>', activate, name='activate')
]

eventmgmt/urls.py
"""
  Urls file docs
"""
from django.urls import path
from eventmgmt import views

urlpatterns = [
    path("my/event/list", views.BookedEventDetailView.as_view(), name="my-event-list"),

    path("new/event/booking/list", views.NewBookingEventView.as_view(), name="new-event-booking"),

    path('new/event/booking/seat/<int:event_id>/', views.SeatBookingView.as_view(),
         name="seat-booking"),
    path('new/event/cancel/seat/<int:booked_event_id>/', views.SeatCancelView.as_view(),
         name="seat-cancel"),

]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600,700&display=swap" rel="stylesheet">
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
        <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

        <link rel="stylesheet" type="text/css" href="{% static 'lib/slick/slick.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'lib/slick/slick-theme.css' %}">

        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

    <title>Event Management</title>
</head>
<body>

    {% include "header.html" %}

<!--Messages-->
{% if messages %}
  {% for message in messages %}
    <div class="alert alert-dismissible alert-{{message.tags}}">
      <button type="button" class="close" data-dismiss="alert">× </button>
      <strong>{{message}}<strong>
    </div>
 {% endfor %}
{% endif %}
<!--End message-->

<!-- Vertically centered modal -->
{% block content %}
{% endblock %}
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>
</html>

templates/dashboard.html
{% extends "base.html" %}

{% load static %}

{% block pagetitle %}
    <title>Dashboard</title>
{% endblock %}


{% block content %}
{% endblock %}

templates/email.html
{% autoescape off %}
Hi ,
Please click on the link to confirm your registration,
{% endautoescape %}

templates/header.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'accountmgmt:home' %}">
        Home
    </a>
    <a class="navbar-brand" href="{% url 'eventmgmt:my-event-list' %}">
        My Booked Events
    </a>
    <a class="navbar-brand" href="{% url 'eventmgmt:new-event-booking' %}">
        Event Booking
    </a>

    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
        </div>
        <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
            <ul class="navbar-nav ml-auto">
                {% if request.user.is_authenticated %}
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle text-white" data-toggle="dropdown">
                            {{request.user}}
                        </a>
                        <div class="dropdown-menu" style="margin: 0px -100%;">
                            <a href="{% url 'accountmgmt:logout' %}" class="dropdown-item">
                                Logout
                            </a>
                        </div>
                    </div>
                {% else %}
                    <li class="nav-item p-1" >
                        <a href="{% url 'accountmgmt:login' %}" class="text-white">Login</a>
                    </li>
                    <li class="nav-item p-1">
                        <a href="{% url 'accountmgmt:signup' %}" class="text-white" >Signup</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

templates/home.html
{% include 'base.html' %}

<div>
    {% if request and request.user %}
        Hello <b>{{request.user.username}},</b>
    {% endif %}
    <p>
        Welcome to Event Booking management Portal.
    </p>
</div>